#####################################################
#                Build Cribl Environment            #
#####################################################
# To run this script:
# docker-compose up -d --scale workers=2 --scale edge=2
# *********************** CREDS ************************ 
# keycloak user: keycloakadmin; password: Sup3rS3cure#2
# minio default user: minioadmin; password: minioadmin
# cribl default user: admin; password: CriblAdmin123
# grafana user: admin; password: Sup3rS3cure#2
# ******************************************************  

services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=keycloakadmin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=Sup3rS3cure#2
    command: start-dev
    volumes:
      - "~/Downloads/cribl-practice/configs/keycloak-data:/opt/keycloak/data"
    restart: always

  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    command: server --console-address ":9090" /minio/mnt/data
    ports:
      - "9001:9000"
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9090/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - "~/Downloads/cribl-practice/configs/minio-data:/minio/mnt/data"
      - "~/Downloads/cribl-practice/configs/minio-config:/minio/etc/config.env"

  stream:
    build: .
    user: cribl:cribl
    restart: unless-stopped
    environment:
      - CRIBL_DIST_MODE=master
      - CRIBL_DIST_MASTER_URL=tcp://criblstream@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - VIRTUAL_HOST=localhost
    ports:
      - "19000:9000"
    volumes:
      - "~/Downloads/cribl-practice/configs/cribl-config:/opt/cribl/config-volume"
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_READ_SEARCH
      - CAP_SYS_PTRACE

  workers:
    build: .
    user: cribl:cribl
    restart: unless-stopped
    depends_on: 
      - stream
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblstream@stream:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/worker-config
    volumes:
      - "~/Downloads/cribl-practice/configs/cribl-data:/opt/cribl/worker-volume"
    ports:
      - "9000"

  edge:
    build: .
    user: cribl:cribl
    restart: unless-stopped
    depends_on: 
      - stream
    environment:
      - CRIBL_DIST_MODE=managed-edge
      - CRIBL_DIST_MASTER_URL=tcp://criblstream@stream:4200?group=default_fleet
      - CRIBL_VOLUME_DIR=/opt/cribl/edge-config
    volumes:
      - "~/Downloads/cribl-practice/configs/edge-data:/opt/cribl/edge-volume"
    ports:
      - "9420"

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - '9080:9080'
    volumes:
      - "~/Downloads/cribl-practice/configs/prom-data:/etc/prometheus"

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    depends_on: 
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - "~/Downloads/cribl-practice/configs/grafana-data:/var/lib/grafana"